# 이 워크플로우는 ci.yml의 e2e-tests 작업에 통합되었습니다.
name: Playwright Tests (비활성화됨)
on:
  # 트리거 비활성화 - ci.yml에 통합됨
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    
    # 의존성 설치 및 shared 패키지 빌드
    - name: Install dependencies
      run: |
        HUSKY=0 npm ci
        cd shared
        npm ci
        npm run build
        cd ..
    
    # Playwright 설치
    - name: Install Playwright Browsers
      run: |
        cd frontend
        npx playwright install --with-deps
    
    # 기능 테스트만 실행 (시각적 테스트 제외)
    - name: Run Playwright tests
      run: |
        cd frontend
        npx playwright test e2e/todo.spec.ts
    
    # 테스트 결과 아티팩트 업로드
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
